### ISSUE TITLE
missing: minimum version compatibility 

### ISSUE THREAD

**Issue by laurentopia** [needle-tools/compilation-visualizer#1]

**Comment by hybridherbst** [comment]
@laurentopia mind being a bit more specific? I assume you're talking about adding that to the Readme instead of only on the package.json?

(I'll add it to the readme later but the OpenUPM interface pulls the version information in already: https://openupm.com/packages/com.needle.compilation-visualizer/)

**Comment by laurentopia** [comment]
yes, min version with a few lines to the top of the readme. there are so many live versions of unity, each with their own pros and cons, that project may be stuck out of reach of this repo

**Comment by hybridherbst** [comment]
Added & tested support for 2018.4 — 2020.2.
Before 2018.4 the relevant APIs don't exist. 
Added a nice badge to the Readme :)
